---
apiVersion: v1
kind: Namespace
metadata:
  name: spring-petclinic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-app-deployment
  namespace: spring-petclinic
  labels:
    app: spring-petclinic-app
spec:
  selector:
    matchLabels:
        app: spring-petclinic-app
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: spring-petclinic-app
    spec:
      containers:
        - name: spring-petclinic-app
          image: 390585564163.dkr.ecr.ap-south-1.amazonaws.com/spring-petclinic:latest
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: java-app-service
  namespace: spring-petclinic
spec:
  selector:
    app: spring-petclinic-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
